title: IT-блог
description: > # this means to ignore newlines until "baseurl:"
  AhengLiux  个人主页<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.weibo.com/u/6056434188" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'AChengLinux'
  last_name: 'AChengLinux'
  cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  kaptn3  
  email: 2041807672@qq.com
  vk_id: id201664979
  telegram_name: AChengLinux 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


